### ISSUE TITLE
File preview in workflow attachment

### ISSUE THREAD

**Issue by git-anurag-hub** [elixir-cloud-aai/krini#2]
**Is your feature request related to a problem? Please describe.**
On the workflow attachment field while running the new workflow it will be great to show the preview of the files irrespective of their type. For now, only the files with the type image will have their preview shown. 

**Describe the solution you'd like**
I think right now we use the library for inputting the fields which shows the preview for the images but returns empty in case of any other file. We can use some sort of library or function to make the preview for any of the files i.e., not the image. 

**Describe alternatives you've considered**
--NA--

**Additional context**'
--NA--

**Comment by tanya17-05** [comment]
Hi Anurag, I want to work on this issue. Can you please assign it to me?
