### ISSUE TITLE
Table from manage workflow section of Krini is not showing responsive behavior

### ISSUE THREAD

**Issue by tanya17-05** [elixir-cloud-aai/krini#5]
**Issue**
Table from manage workflow section of Krini is not showing responsive behavior (the table is overflowing outside the container div)

**Steps to reproduce the behavior:**
1. Go to '[Krini > Manage Workflows](https://krini.rahtiapp.fi/manage)'
2. Use devtools to observe the  page in different devices

**Screenshots**
![localhost_3000_manage(iPhone SE)](https://user-images.githubusercontent.com/95133237/185054072-61ea7014-a1e7-405d-9f31-b1680f390ad3.png)

**Smartphone:**
 - Device: All devices under width 573px

**Comment by uniqueg** [comment]
Thanks a lot @tanya17-05! Do you think you could work on fixing that? :)

**Comment by tanya17-05** [comment]
@uniqueg I am on it :)

**Comment by tanya17-05** [comment]
Changing font size affected readability so I've made the table horizontally scrollable.
